import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { TicketProvider } from './ticketcontext.js';  // Adjust the import path as necessary


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TicketProvider>
          {children}
        </TicketProvider>
      </body>
    </html>
  );
}
